//! Cross-platform golden protocol vectors.
//!
//! `testvectors/packets.json` is the canonical set of encoded packets, generated here and
//! consumed by every implementation (this Rust crate today; the Kotlin/JVM and Swift test
//! targets in later milestones). If the wire format changes, these must be regenerated *and* the
//! protocol version bumped — CI diffs the committed file against freshly-generated bytes, so an
//! accidental format change fails the build.
//!
//! Regenerate after an intentional format change:  `REGEN_VECTORS=1 cargo test -p meshcore --test vectors`

use meshcore::identity::LocalIdentity;
use meshcore::wire::{MsgType, Packet};
use serde_json::{json, Value};

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

/// Deterministically build the canonical packet set. Ed25519 signatures are deterministic
/// (RFC 8032), so identical (seed, message) inputs always yield identical bytes.
fn build_vectors() -> Vec<Value> {
    let id = LocalIdentity::from_seed(&[0x11; 32]);
    let sender = id.eph_id();

    let mut out = Vec::new();

    let mut push = |name: &str, desc: &str, mut pkt: Packet| {
        pkt.sign(id.signing_key());
        let bytes = pkt.encode();
        // Sanity: it must decode back to an equal packet.
        assert_eq!(Packet::decode(&bytes).unwrap(), pkt, "roundtrip for {name}");
        out.push(json!({
            "name": name,
            "description": desc,
            "version": pkt.version,
            "type": pkt.msg_type.to_u8(),
            "ttl": pkt.ttl,
            "sender": hex_encode(&pkt.sender),
            "hex": hex_encode(&bytes),
            "digest": hex_encode(&pkt.digest()),
        }));
    };

    push(
        "channel_broadcast",
        "A public channel message with no recipient (broadcast).",
        Packet::new(
            MsgType::ChannelMessage,
            7,
            1_700_000_000_000,
            sender,
            None,
            b"hello mesh".to_vec(),
        ),
    );
    push(
        "direct_message",
        "A directed packet carrying an 8-byte recipient ephemeral id.",
        Packet::new(
            MsgType::DirectMessage,
            5,
            1_700_000_000_001,
            sender,
            Some([0xAB; 8]),
            b"ciphertext-goes-here".to_vec(),
        ),
    );
    push(
        "announce",
        "An identity announce carrying an opaque payload.",
        Packet::new(
            MsgType::Announce,
            7,
            1_700_000_000_002,
            sender,
            None,
            vec![0x01, 0x02, 0x03, 0x04],
        ),
    );
    push(
        "unknown_type_preserved",
        "An unknown message type (0x7f) — relays must forward it unparsed.",
        Packet::new(
            MsgType::Unknown(0x7f),
            3,
            1_700_000_000_003,
            sender,
            None,
            vec![0xDE, 0xAD, 0xBE, 0xEF],
        ),
    );
    push(
        "empty_payload",
        "A zero-length payload (boundary case for the decoder).",
        Packet::new(MsgType::Receipt, 1, 1_700_000_000_004, sender, None, vec![]),
    );

    out
}

fn vectors_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testvectors/packets.json")
}

#[test]
fn golden_vectors_match() {
    let vectors = build_vectors();
    let doc = json!({
        "protocol_version": meshcore::wire::PROTOCOL_VERSION,
        "note": "Canonical wire vectors. Regenerate with REGEN_VECTORS=1; bump protocol_version on any change.",
        "packets": vectors,
    });
    let path = vectors_path();

    if std::env::var("REGEN_VECTORS").is_ok() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            format!("{}\n", serde_json::to_string_pretty(&doc).unwrap()),
        )
        .unwrap();
        eprintln!("regenerated {}", path.display());
        return;
    }

    let golden: Value = serde_json::from_str(
        &std::fs::read_to_string(&path)
            .expect("testvectors/packets.json missing; run with REGEN_VECTORS=1"),
    )
    .expect("packets.json is not valid JSON");

    assert_eq!(
        golden["packets"],
        Value::Array(vectors.clone()),
        "wire format drifted from the golden vectors — if intentional, bump PROTOCOL_VERSION and regenerate"
    );

    // Independently confirm every golden hex string decodes to the stated digest.
    for v in golden["packets"].as_array().unwrap() {
        let bytes = hex_decode(v["hex"].as_str().unwrap());
        let pkt = Packet::decode(&bytes).expect("golden hex must decode");
        assert_eq!(hex_encode(&pkt.digest()), v["digest"].as_str().unwrap());
    }
}
